backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/images/uploads" # Media files will be stored in the repo under public/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", format: "DD MMM, YYYY", date_format: "DD MMM, YYYY", time_format: false}
      - {label: "Read Time", name: "readTime", widget: "string", default: "5 min read"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Cover Image", name: "coverImage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
